### ISSUE TITLE
github actions error in the script section

### ISSUE THREAD

**Issue by hthre7** [AppImageCrafters/appimage-builder#107]
trying to build using Github Actions but there is an error (rm and mkdir work without any issue)
what I tried ( --prefix=/usr) (/usr/bin/meson) but still the same result

```sh
rm -rf AppDir | true
rm -rf build  | true
mkdir build
meson build --prefix=/usr/bin/
bash: line 4: meson: command not found
Traceback (most recent call last):
  File "/usr/local/bin/appimage-builder", line 11, in <module>
    load_entry_point('appimage-builder==0.8.5', 'console_scripts', 'appimage-builder')()
  File "/usr/local/lib/python3.6/dist-packages/appimage_builder-0.8.5-py3.6.egg/appimagebuilder/__main__.py", line 90, in __main__
    shell.execute(script_instructions, env={"APPDIR": os.path.abspath(appdir)})
  File "/usr/local/lib/python3.6/dist-packages/appimage_builder-0.8.5-py3.6.egg/appimagebuilder/common/shell.py", line 51, in execute
    raise RuntimeError("Script exited with code: %s" % _proc.returncode)
RuntimeError: Script exited with code: 127
```

**Comment by azubieta** [comment]
`bash: line 4: meson: command not found`
 
You need to install meson inside the docker image in order to use it, this can be done by running apt-get from the script section

**Comment by hthre7** [comment]
tried to include (`apt install meson`) inside appimagebuilder.yml(recipe) however it using(ubuntu 18.04)(meson 0.45) but the needed version is (meson 0.50 or more), so instead of using docker github actions I used the following:
N.B:could you update appimage-build Github action(https://github.com/marketplace/actions/build-appimage) it's using appimage-builder 0.82.
here what I used
```sh
      - name: appimagetool
        run: |
           sudo wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O /usr/local/bin/appimagetool
           sudo chmod +x /usr/local/bin/appimagetool
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install appimage-builder
        run: yes | sudo pip3 install git+https://github.com/AppImageCrafters/appimage-builder.git
      
      - name: Build AppImage
        run: appimage-builder --recipe AppImageBuilder.yml --skip-test 
```

**Comment by azubieta** [comment]
You could also use the appimage-builder AppImage from https://github.com/AppImageCrafters/appimage-builder/releases/tag/v0.8.6
