### ISSUE TITLE
appimage-builder stuck following the tutorial

### ISSUE THREAD

**Issue by diamant711** [AppImageCrafters/appimage-builder#116]
Hi to everyone!
OS: Arch Linux x86_64
Kernel: 5.11.11-arch1-1
Terminal: alacritty (with fish)
Full log following the tutorial:
```
~/testAppImage 2ms
> git clone https://www.opencode.net/azubieta/qt-appimage-template.git
Clone in 'qt-appimage-template' in corso...
remote: Enumerating objects: 60, done.
remote: Counting objects: 100% (60/60), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 60 (delta 26), reused 44 (delta 17)
Decompressione degli oggetti in corso: 100% (60/60), 31.17 KiB | 2.60 MiB/s, fatto.

~/testAppImage 1s5ms
> cd qt-appimage-template

.../qt-appimage-template   master
> cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.11")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/diamant/Progetti/OpenProgrammer/testAppImage/qt-appimage-template

.../qt-appimage-template 2s654ms  master [?]
> make install DESTDIR=AppDir
[ 16%] Automatic MOC and UIC for target qt-appimage-template
[ 16%] Built target qt-appimage-template_autogen
[ 33%] Automatic RCC for qml.qrc
[ 50%] Building CXX object src/CMakeFiles/qt-appimage-template.dir/qt-appimage-template_autogen/mocs_compilation.cpp.o
[ 66%] Building CXX object src/CMakeFiles/qt-appimage-template.dir/main.cpp.o
[ 83%] Building CXX object src/CMakeFiles/qt-appimage-template.dir/qt-appimage-template_autogen/EWIEGA46WW/qrc_qml.cpp.o
[100%] Linking CXX executable qt-appimage-template
[100%] Built target qt-appimage-template
Install the project...
-- Install configuration: "Release"
-- Installing: AppDir/usr/bin/qt-appimage-template
-- Installing: AppDir/usr/share/applications/QtQuickControls2Application.desktop
-- Installing: AppDir/usr/share/icons/hicolor/256x256/apps/QtQuickControls2Application.png

.../qt-appimage-template 6s35ms  master [?]
> appimage-builder --generate
INFO:Generator:Searching AppDir
INFO:Generator:Searching desktop entries
INFO:Generator:Reading desktop entry: /home/diamant/Progetti/OpenProgrammer/testAppImage/qt-appimage-template/AppDir/usr/share/applications/QtQuickControls2Application.desktop
Basic Information :
? ID [Eg: com.example.app] : QtQuickControls2Application
? Application Name : SimpleQtApp
? Icon : QtQuickControls2Application
? Version : latest
? Executable path relative to AppDir [usr/bin/app] : usr/bin/qt-appimage-template
? Arguments [Default: $@] : $@
? Update Information [Default: guess] : guess
? Architecture : amd64
INFO:Generator:Analysing application runtime dependencies
INFO:AppRuntimeAnalyser:/usr/bin/strace -ff -e trace=openat -E LD_LIBRARY_PATH= /home/diamant/Progetti/OpenProgrammer/testAppImage/qt-appimage-template/AppDir/usr/bin/qt-appimage-template $@
```
If i send a SIGINT with ctrl+c i recive this log:
```
^CTraceback (most recent call last):
  File "/usr/bin/appimage-builder", line 8, in <module>
    sys.exit(__main__())
  File "/usr/lib/python3.9/site-packages/appimagebuilder/__main__.py", line 77, in __main__
    generator = RecipeGenerator()
  File "/usr/lib/python3.9/site-packages/appimagebuilder/generator/generator.py", line 63, in __init__
    required_files = runtime_analyser.run_app_analysis()
  File "/usr/lib/python3.9/site-packages/appimagebuilder/generator/app_runtime_analyser.py", line 47, in run_app_analysis
    _proc = subprocess.run(command, stderr=subprocess.PIPE, shell=True)
  File "/usr/lib/python3.9/subprocess.py", line 507, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.9/subprocess.py", line 1124, in communicate
    stderr = self.stderr.read()
KeyboardInterrupt
```
Anyone can help me?
Thanks in advance!

**Comment by azubieta** [comment]
Hi, the tutorial is meant to be ran in a Ubuntu/Debian system were apt-get is available. Anyway it should not get stuck in the generate step, I'll take a look at it.

**Comment by azubieta** [comment]
Hello, could you please make sure that the app runs properly before calling `appimage-builder --generate`?

If the QtQuick Qml module is not present in your system the app runs but doesn't show up.

**Comment by diamant711** [comment]
You're right! This step is succesfully pass. But now i'm stuck in another point. Should i open a new Issue, or maybe we can continue here?

**Comment by azubieta** [comment]
Let's open a new issue so this can be used by others in the same situation.
