### ISSUE TITLE
Cannot try examples

### ISSUE THREAD

**Issue by antony-jr** [AppImageCrafters/appimage-builder#12]
I installed ```appimage-builder``` through pip and tried it out on the examples. But I cannot get any example to work.
It says,
```
INFO:apt-key:fakeroot apt-key --keyring /home/antonyjr/Developer/AppImageUpdater/appimage-builder-cache/etc/apt/trusted.gpg add -
Traceback (most recent call last):
  File "/usr/bin/appimage-builder", line 18, in <module>
    __main__();
  File "/usr/lib/python3.8/site-packages/AppImageBuilder/__main__.py", line 54, in __main__
    builder.build()
  File "/usr/lib/python3.8/site-packages/AppImageBuilder/app_dir/builder.py", line 56, in build
    self.apt_config.generate()
  File "/usr/lib/python3.8/site-packages/AppImageBuilder/app_dir/apt_bundler/config.py", line 52, in generate
    self._generate_apt_keyring()
  File "/usr/lib/python3.8/site-packages/AppImageBuilder/app_dir/apt_bundler/config.py", line 156, in _generate_apt_keyring
    self._add_apt_key(key_url, keyring_path)
  File "/usr/lib/python3.8/site-packages/AppImageBuilder/app_dir/apt_bundler/config.py", line 167, in _add_apt_key
    apt_key.add(key, keyring_path)
  File "/usr/lib/python3.8/site-packages/AppImageBuilder/commands/apt_key.py", line 28, in add
    raise AptKeyError('apt-key add failed')
AppImageBuilder.commands.apt_key.AptKeyError: apt-key add failed
```

**Comment by azubieta** [comment]
Are you using a debian, ubuntu or something alike? `appimage-builder` relies on the system apt installation to work.

**Comment by antony-jr** [comment]
Sorry I found that out when I looked at the source code. I use archlinux, So that explains.

**Comment by azubieta** [comment]
Sorry for the inconvenient, I know that better documentation is required. In the meantime, you can use a docker container.
