### ISSUE TITLE
Desktop entry file not found.

### ISSUE THREAD

**Issue by vuvko** [AppImageCrafters/appimage-builder#120]
While running `appimage-builder --generate` I was presented with two options as the main entry: one was found in `AppDir` folder, the other inside `AppDir/usr/share/applications`. I wanted to build an application with the first desktop file as an entry point, but `appimage-builder` threw a `KeyError`.

Full traceback:
```
Traceback (most recent call last):
  File "/home/andrey/.local/bin/appimage-builder", line 8, in <module>
    sys.exit(__main__())
  File "/home/andrey/.local/lib/python3.9/site-packages/appimagebuilder/__main__.py", line 77, in __main__
    generator = RecipeGenerator()
  File "/home/andrey/.local/lib/python3.9/site-packages/appimagebuilder/generator/generator.py", line 56, in __init__
    self._setup_app_info()
  File "/home/andrey/.local/lib/python3.9/site-packages/appimagebuilder/generator/generator.py", line 201, in _setup_app_info
    parser = DesktopFileParser(desktop_file)
  File "/home/andrey/.local/lib/python3.9/site-packages/appimagebuilder/generator/desktop_entry_parser.py", line 25, in __init__
    exec = self.parser["Desktop Entry"]["Exec"].strip()
  File "/usr/lib/python3.9/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'Desktop Entry'

```

It seems that the reason for this is [this](https://github.com/AppImageCrafters/appimage-builder/blob/4e7c15ff65a8f9516adf241e73fe4b86e3915c83/appimagebuilder/generator/generator.py#L217) line. While appending path to the file, the root's absolute path is not added.

**Comment by azubieta** [comment]
Hello @vuvko thanks for reporting and taking a look into it. I'll fix it ASAP.

**Comment by vuvko** [comment]
@azubieta 
It's one line fix, but now this works for my case. Here's the PR: https://github.com/AppImageCrafters/appimage-builder/pull/121.
I can close this issue if it's OK with you.

**Comment by azubieta** [comment]
Thanks again!
