### ISSUE TITLE
No runtime when building on arm64

### ISSUE THREAD

**Issue by TIS-Edgar** [AppImageCrafters/appimage-builder#137]
When executing `appimage-builder --recipe ./appimage-recipe.yml` I get the following error.

```
INFO:main:Running deploy record generation
INFO:root:Writing deploy record to: .bundle.yml
INFO:main:Running AppImage creation
ERROR:root:There is not a prebuild runtime for the arm64 architecture. You will have to build the AppImage runtime manually.
INFO:root:Downloading runtime: https://github.com/AppImage/AppImageKit/releases/download/continuous/runtime-arm64
Traceback (most recent call last):
  File "/usr/local/bin/appimage-builder", line 11, in <module>
    sys.exit(__main__())
  File "/usr/local/lib/python3.6/dist-packages/appimagebuilder/__main__.py", line 57, in __main__
    invoker.execute(commands)
  File "/usr/local/lib/python3.6/dist-packages/appimagebuilder/invoker.py", line 41, in execute
    command()
  File "/usr/local/lib/python3.6/dist-packages/appimagebuilder/commands/create_appimage.py", line 27, in __call__
    creator.create()
  File "/usr/local/lib/python3.6/dist-packages/appimagebuilder/modules/appimage.py", line 52, in create
    self._download_runtime_if_required(runtime_path, runtime_url)
  File "/usr/local/lib/python3.6/dist-packages/appimagebuilder/modules/appimage.py", line 68, in _download_runtime_if_required
    request.urlretrieve(runtime_url, runtime_path)
  File "/usr/lib/python3.6/urllib/request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

```

Looking at the continuous builds under https://github.com/AppImage/AppImageKit/releases/ appimagekit seems to refer to arm64 as aarch64.

appimage has been installed according to the documentation (https://appimage-builder.readthedocs.io/en/latest/intro/install.html#installing-dependencies).
Should it be relevant the plattform I am building on is a NVidia Jetson Nano (Ubuntu 18.04 LTS).

Do you need any additional information?

**Comment by azubieta** [comment]
@TIS-Edgar sorry for the late response, are you setting the `AppImage > architecture` field to `aarch64` ?

**Comment by TIS-Edgar** [comment]
Your question showed that I had a mistake in that field...

Since die dependency description requires arm64 I mistakenly assumed that would be the case everywhere.
The examples also correctly show what to use where.
Sorry for taking your time.

For reference here is a working example of my arm64 recipe:

```
version: 1
script: |
  rm -rf ./AppDir | true
  # compile and install binaries into AppDir
  cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
  make install DESTDIR=AppDir
  dpkg-deb -x local_deb_arm64.deb AppDir

AppDir:
  path: ./AppDir

  app_info:
    id: my-app
    name: my-app
    icon:  system-file-manager
    version: 1.0.1
    exec: usr/bin/my-app
    exec_args: $@

  apt:
    arch: arm64
    sources:
      - sourceline: 'deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports focal main universe restricted'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3b4fe6acc0b21f32'
    include:
      - coreutils
      - dash
      - bash
      - libqt5x11extras5
      - libqt5concurrent5
      - libqt5core5a
      - libqt5dbus5
      - libqt5gui5
      - libqt5network5
      - libqt5printsupport5
      - libqt5sql5
      - libqt5test5
      - libqt5widgets5
      - libqt5xml5
      - libqt5opengl5
      - libglu1-mesa
      - libegl1-mesa
      - libdrm2
      - libgbm1
      - libxcb-render0
      - libx11-xcb1
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libglx0
      - libgl1
      - libxcb1
      - libicu66
      - libglvnd0
      - libglew2.1
      - libxau6
      - libx11-6
      - libxrender1
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - libgstreamer-plugins-base1.0-0
      - gstreamer1.0-x
      - gstreamer1.0-gl
      - libgstreamer1.0-0
      - libgstreamer-gl1.0-0
      - libopengl0
      - libusb-1.0-0
      - libzip5
      - libglib2.0-0
      - libgirepository-1.0-1
      - libudev1
      - libpcap0.8
    exclude:
      - dpkg
      - perl-base
      - libperl5.30
      - perl-modules-5.30
      - perl-doc
      - libtest-harness-perl
      - pkg-config
      - python3
      - python3.6
      - qt5-qmake
      - libbluray2
      - adwaita-icon-theme
      - ubuntu-mono_19.04
      - libncurses
  files:
    exclude:
      - usr/bin/pkg-config
      - usr/lib/x86_64-linux-gnu/gconv
      - usr/share/man/*
      - usr/share/doc/*
      - usr/share/locales/*
      # gstreamer libraries that cause problems because they can't find dependencies
      # remove them as we do not use them
      - usr/lib/*/gstreamer-1.0/libgstx265.so
      - usr/lib/*/gstreamer-1.0/libgstresindvd.so
      - usr/lib/*/gstreamer-1.0/libgstdvdread.so
      - usr/lib/*/gstreamer-1.0/libgstcdio.so
      - usr/lib/*/gstreamer-1.0/libgstv4l2.so

  runtime:
    path_mappings:
      - /dev/:$APPDIR/dev
    env:
      QT_PLUGIN_PATH: '${APPDIR}/usr/lib/aarch64-linux-gnu/qt5/plugins/'
      PATH: '${APPDIR}/usr/bin:${PATH}'
      LIBRARY_PATH: ' $APPDIR/lib/aarch64-linux-gnu:${APPDIR}/usr/lib/${APPDIR}/usr/lib/aarch64-linux-gnu/:${LIBRARY_PATH}'
      LD_LIBRARY_PATH: '${APPDIR}/usr/lib/${APPDIR}/usr/lib/aarch64-linux-gnu/:${LD_LIBRARY_PATH}'
      GST_PLUGIN_PATH_1_0: '${APPDIR}/lib/aarch64-linux-gnu/gstreamer-1.0:${GST_PLUGIN_PATH_1_0}'

AppImage:
  update-information: None
  sign-key: None
  arch: aarch64

```

**Comment by azubieta** [comment]
@TIS-Edgar no worries.

By the way you can omit defining the LD_LIBRARY_PATH, appimage-builder sets it to all the folders where it founds a so file.
