### ISSUE TITLE
Adding sign-key causes TypeError

### ISSUE THREAD

**Issue by h-b** [AppImageCrafters/appimage-builder#151]
As soon as I add an entry `sign-key` in my `AppImageBuilder.yml`, as described in section 2.15.2 of [the documentation](https://appimage-builder.readthedocs.io/_/downloads/en/latest/pdf/) I am getting this error:

    INFO:root:Generating AppImage from AppDir
    Traceback (most recent call last):
      File "/usr/local/bin/appimage-builder", line 11, in <module>
        sys.exit(__main__())
      File "/home/stefan/.local/lib/python3.6/site-packages/appimagebuilder/__main__.py", line 58, in __main__
        invoker.execute(commands)
      File "/home/stefan/.local/lib/python3.6/site-packages/appimagebuilder/invoker.py", line 41, in execute
        command()
      File "/home/stefan/.local/lib/python3.6/site-packages/appimagebuilder/commands/create_appimage.py", line 27, in __call__
        creator.create()
      File "/home/stefan/.local/lib/python3.6/site-packages/appimagebuilder/modules/appimage.py", line 54, in create
        self._generate_appimage(runtime_path)
      File "/home/stefan/.local/lib/python3.6/site-packages/appimagebuilder/modules/appimage.py", line 63, in _generate_appimage
        appimage_tool.run()
      File "/home/stefan/.local/lib/python3.6/site-packages/appimagebuilder/gateways/appimagetool.py", line 39, in run
        self._run(command)
      File "/home/stefan/.local/lib/python3.6/site-packages/appimagebuilder/gateways/command.py", line 53, in _run
        self.logger.info(" ".join(command))
    TypeError: sequence item 5: expected str instance, Roamer found

Without the entry, the AppImage is generated successfully (including zsync update info, menu icon, everything works perfectly). gpg and gpg2 are installed and the key I am using is valid. When testing with an invalid key, the same error occurs. Version info:

    $ appimagetool --version
    appimagetool, continuous build (commit 1681fd8), build <local dev build> built on 2021-06-09 06:11:53 UTC
    $ pip3 list | grep appimage-builder
    appimage-builder (0.9.1)

**Comment by azubieta** [comment]
@h-b This is a regression bug, I just pushed a fix to master. Could you please try again ?

**Comment by h-b** [comment]
Thanks a lot, this seems to fix it. I am not sure if the subsequent error I am getting is related to this. Generation proceeds,  the argument `--sign-key ...` is passed to appimagetool, but signing fails:

    WARNING:appimagetool:Embedding MD5 digest
    WARNING:appimagetool:gpg2 and sha256sum are installed and user requested to sign, hence signing
    WARNING:appimagetool:sha256sum command did not succeed
    ERROR:root:AppImage generation failed

I am successfully using this key to sign mails. The output of `gpg --list-keys` looks okay and I copied the key from the output of that command to `AppImageBuilder.yml`. When I sign manually via `gpg2 --sign my.AppImage` both

- `sha256sum my.AppImage.gpg` and
- `gpg2 --verify my.AppImage.gpg`

succeed. I am not experienced with signing, currently investigating this further...

**Comment by azubieta** [comment]
@h-b this may be an issue on appimagetool itself. Could you please try calling `appimagetool` on your AppDir manually, and share the output?

Here are some instructions on how to use appimagetool to sign:

https://docs.appimage.org/packaging-guide/optional/signatures.html?highlight=sign#embedding-a-signature-inside-an-appimage

**Comment by azubieta** [comment]
@h-b Also make sure your are passing your secret key id. Use `gpg2 --list-secret-keys` to the the right list.

I'll close this as solved. Please feel free to reopen if required.
