### ISSUE TITLE
`os.symlink` error `File exists`

### ISSUE THREAD

**Issue by azubieta** [AppImageCrafters/appimage-builder#153]
I will package a flutter desktop application.
I installed last version from git.  don't pacman error, but i got a new error.

my step:
1.  mkdir package && cp -r ../build/linux/x64/release/bundle ./AppDir   
2.  sudo /usr/local/python3.8/bin/appimage-builder --generate       is ok
3. $ sudo /usr/local/python3.8/bin/appimage-builder --recipe AppImageBuilder.yml

error:
`Traceback (most recent call last):
  File "/usr/local/python3.8/bin/appimage-builder", line 11, in <module>
    load_entry_point('appimage-builder==0.9.1', 'console_scripts', 'appimage-builder')()
  File "/usr/local/python3.8/lib/python3.8/site-packages/appimagebuilder/__main__.py", line 58, in __main__
    invoker.execute(commands)
  File "/usr/local/python3.8/lib/python3.8/site-packages/appimagebuilder/invoker.py", line 41, in execute
    command()
  File "/usr/local/python3.8/lib/python3.8/site-packages/appimagebuilder/commands/pacman_deploy.py", line 50, in __call__
    deployed_packages = pacman_deploy.deploy(
  File "/usr/local/python3.8/lib/python3.8/site-packages/appimagebuilder/modules/deploy/pacman/deploy.py", line 89, in deploy
    os.symlink("usr/lib", appdir_root / "lib")
FileExistsError: [Errno 17] File exists: 'usr/lib' -> '/data/flutterWork/desktop/rename_exif/package/AppDir/lib'
`

_Originally posted by @colatea in https://github.com/AppImageCrafters/appimage-builder/issues/136#issuecomment-908025979_

**Comment by JartX** [comment]
Same problem here:

Traceback (most recent call last):
  File "/usr/bin/appimage-builder", line 8, in <module>
    sys.exit(__main__())
  File "/usr/lib/python3.9/site-packages/appimagebuilder/__main__.py", line 58, in __main__
    invoker.execute(commands)
  File "/usr/lib/python3.9/site-packages/appimagebuilder/invoker.py", line 41, in execute
    command()
  File "/usr/lib/python3.9/site-packages/appimagebuilder/commands/pacman_deploy.py", line 50, in __call__
    deployed_packages = pacman_deploy.deploy(
  File "/usr/lib/python3.9/site-packages/appimagebuilder/modules/deploy/pacman/deploy.py", line 89, in deploy
    os.symlink("usr/lib", appdir_root / "lib")
FileExistsError: [Errno 17] File exists: 'usr/lib'

**Comment by azubieta** [comment]
@JartX could you please try again using the `fix/properly_recreate_archfs_structure` branch ?

`pip install git+https://github.com/AppImageCrafters/appimage-builder.git@fix/properly_recreate_archfs_structure`

**Comment by JartX** [comment]
> @JartX could you please try again using the `fix/properly_recreate_archfs_structure` branch ?
> 
> `pip install git+https://github.com/AppImageCrafters/appimage-builder.git@fix/properly_recreate_archfs_structure`

Same problem: 
INFO:PacmanPackageDeploy:Deploying glibc=2.33-5 to /home/jart/DEV/usbserial_appimage/AppDir/opt/libc
Traceback (most recent call last):
  File "/usr/bin/appimage-builder", line 8, in <module>
    sys.exit(__main__())
  File "/usr/lib/python3.9/site-packages/appimagebuilder/__main__.py", line 58, in __main__
    invoker.execute(commands)
  File "/usr/lib/python3.9/site-packages/appimagebuilder/invoker.py", line 41, in execute
    command()
  File "/usr/lib/python3.9/site-packages/appimagebuilder/commands/pacman_deploy.py", line 50, in __call__
    deployed_packages = pacman_deploy.deploy(
  File "/usr/lib/python3.9/site-packages/appimagebuilder/modules/deploy/pacman/deploy.py", line 91, in deploy
    os.symlink("lib", appdir_root / "usr" / "lib64")
FileNotFoundError: [Errno 2] No such file or directory: 'lib' -> '/home/jart/DEV/usbserial_appimage/AppDir/usr/lib64

**Comment by azubieta** [comment]
@JartX it seems that you're still using the older version of appimage-builder
