### ISSUE TITLE
403 forbidden while fetching libapprun_hooks-Release-x86_64.so

### ISSUE THREAD

**Issue by alex-tee** [AppImageCrafters/appimage-builder#161]
```
...
WARNING:root:Required interpreter 'sh' could not be found in the AppDir while processing /tmp/AppDir/usr/bin/zstdgrep
WARNING:root:Required interpreter 'sh' could not be found in the AppDir while processing /tmp/AppDir/usr/bin/gettext.sh
WARNING:root:Required interpreter 'sh' could not be found in the AppDir while processing /tmp/AppDir/usr/bin/bashbug
WARNING:root:Required interpreter 'sh' could not be found in the AppDir while processing /tmp/AppDir/usr/bin/zstdless
INFO:root:Downloading: https://github.com/AppImageCrafters/AppRun/releases/download/v1.2.5/libapprun_hooks-Release-x86_64.so
Traceback (most recent call last):
  File "/usr/local/bin/appimage-builder", line 8, in <module>
    sys.exit(__main__())
  File "/usr/local/lib/python3.8/dist-packages/appimagebuilder/__main__.py", line 58, in __main__
    invoker.execute(commands)
  File "/usr/local/lib/python3.8/dist-packages/appimagebuilder/invoker.py", line 41, in execute
    command()
  File "/usr/local/lib/python3.8/dist-packages/appimagebuilder/commands/setup_runtime.py", line 27, in __call__
    runtime.generate()
  File "/usr/local/lib/python3.8/dist-packages/appimagebuilder/modules/setup/generator.py", line 64, in generate
    self._deploy_appdir_hooks(wrapper, runtime_env, embed_archs)
  File "/usr/local/lib/python3.8/dist-packages/appimagebuilder/modules/setup/generator.py", line 215, in _deploy_appdir_hooks
    wrapper.deploy_hooks_lib(arch, path)
  File "/usr/local/lib/python3.8/dist-packages/appimagebuilder/modules/setup/executables_wrapper.py", line 66, in deploy_hooks_lib
    source_path = self.binaries_resolver.resolve_hooks_library(arch)
  File "/usr/local/lib/python3.8/dist-packages/appimagebuilder/modules/setup/apprun_binaries_resolver.py", line 49, in resolve_hooks_library
    self._download_release_asset(asset, file)
  File "/usr/local/lib/python3.8/dist-packages/appimagebuilder/modules/setup/apprun_binaries_resolver.py", line 59, in _download_release_asset
    request.urlretrieve(url, path)
  File "/usr/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by azubieta** [comment]
Closing this as solved, please feel free to reopen it if required.
