### ISSUE TITLE
Valid yml syntax throwing error

### ISSUE THREAD

**Issue by anupam-git** [AppImageCrafters/appimage-builder#20]
`env: []` is a valid yml syntax but appimage-builder throws an error while building appimage

Stack trace : 
```
Traceback (most recent call last):
  File "/usr/local/bin/appimage-builder", line 18, in <module>
    __main__();
  File "/usr/local/lib/python3.6/dist-packages/AppImageBuilder/__main__.py", line 54, in __main__
    builder.build()
  File "/usr/local/lib/python3.6/dist-packages/AppImageBuilder/app_dir/builder.py", line 81, in build
    runtime.generate()
  File "/usr/local/lib/python3.6/dist-packages/AppImageBuilder/app_dir/runtimes/wrapper/runtime.py", line 42, in generate
    self._add_user_defined_settings(app_run)
  File "/usr/local/lib/python3.6/dist-packages/AppImageBuilder/app_dir/runtimes/wrapper/runtime.py", line 62, in _add_user_defined_settings
    for k, v in self.env.items():
AttributeError: 'list' object has no attribute 'items'
```

**Comment by azubieta** [comment]
Which `env` are you referring to? The `runtime env` or the `test env`?

**Comment by azubieta** [comment]
The runtime env expects a map, the tests env expects a list. So you have to write `env: {}` for an empty one.

Semantically this an error, but the specification is frozen so it will have to wait until the 2
