### ISSUE TITLE
shutil.SameFileError: '/lib64/ld-linux-x86-64.so.2' 

### ISSUE THREAD

**Issue by SahajRana** [AppImageCrafters/appimage-builder#227]
Hi AppImage team, thanks for the library. I'm receiveing this error & can't find a solution to fix this.

Could you help me to understand how to fix this?
Thanks.

```
INFO:FileDeploy:deploying /lib64/ld-linux-x86-64.so.2
Traceback (most recent call last):
  File "/tmp/.mount_appimaLfOdtr/usr/bin/appimage-builder", line 8, in <module>
    sys.exit(__main__())
  File "/tmp/.mount_appimaLfOdtr/usr/lib/python3.8/site-packages/appimagebuilder/__main__.py", line 44, in __main__
    invoker.execute(commands)
  File "/tmp/.mount_appimaLfOdtr/usr/lib/python3.8/site-packages/appimagebuilder/invoker.py", line 29, in execute
    command()
  File "/tmp/.mount_appimaLfOdtr/usr/lib/python3.8/site-packages/appimagebuilder/commands/file_deploy.py", line 29, in __call__
    helper.deploy(self._paths)
  File "/tmp/.mount_appimaLfOdtr/usr/lib/python3.8/site-packages/appimagebuilder/modules/deploy/files/deploy_helper.py", line 119, in deploy
    self._deploy_path(path)
  File "/tmp/.mount_appimaLfOdtr/usr/lib/python3.8/site-packages/appimagebuilder/modules/deploy/files/deploy_helper.py", line 128, in _deploy_path
    shutil.copy2(path, deploy_path)
  File "/tmp/.mount_appimaLfOdtr/usr/lib/python3.8/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/tmp/.mount_appimaLfOdtr/usr/lib/python3.8/shutil.py", line 244, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/lib64/ld-linux-x86-64.so.2' and '/home/ubuntu/StudioProjects/Blup/ide/AppDir/runtime/compat/lib64/ld-linux-x86-64.so.2' are the same file
```

I tried to put this file in `exclude` but didn't work.

```
    exclude:
      - lib64/ld-linux-x86-64.so.2
      - /lib64/ld-linux-x86-64.so.2
      - ...
```

**Comment by realnc** [comment]
I'm getting the same error when running `appimage-builder-1.0.1-253bcb9-x86_64.AppImage` on Ubuntu 22.04.

**Comment by azubieta** [comment]
It seems that the file is being deployed twice will push a fix right away.

**Comment by azubieta** [comment]
@SahajRana could you please check if the issue is corrected in this build:

https://github.com/AppImageCrafters/appimage-builder/actions/runs/2333395061

**Comment by SahajRana** [comment]
Hi @azubieta, thanks for the update. Now, I'm receiving this error.

```
INFO:main:Running apt deploy
Traceback (most recent call last):
  File "/tmp/.mount_appima3Lof9H/usr/bin/appimage-builder", line 8, in <module>
    sys.exit(__main__())
  File "/tmp/.mount_appima3Lof9H/usr/lib/python3.8/site-packages/appimagebuilder/__main__.py", line 44, in __main__
    invoker.execute(commands)
  File "/tmp/.mount_appima3Lof9H/usr/lib/python3.8/site-packages/appimagebuilder/invoker.py", line 29, in execute
    command()
  File "/tmp/.mount_appima3Lof9H/usr/lib/python3.8/site-packages/appimagebuilder/commands/apt_deploy.py", line 42, in __call__
    apt_venv = self._setup_apt_venv()
  File "/tmp/.mount_appima3Lof9H/usr/lib/python3.8/site-packages/appimagebuilder/commands/apt_deploy.py", line 60, in _setup_apt_venv
    apt_venv = Venv(
  File "/tmp/.mount_appima3Lof9H/usr/lib/python3.8/site-packages/appimagebuilder/modules/deploy/apt/venv.py", line 47, in __init__
    self._write_apt_conf(user_options, architectures)
  File "/tmp/.mount_appima3Lof9H/usr/lib/python3.8/site-packages/appimagebuilder/modules/deploy/apt/venv.py", line 87, in _write_apt_conf
    "APT::Architecture": architectures[0],
IndexError: list index out of range
```

**Comment by SahajRana** [comment]
Nevermind the above error. It is resolved & seems like the error has been resolved with the update!

PS: I received the above error because when I did `appimage-builder --generate` 
It created recipe with 

```
 apt:
    arch: []
```
in place of,

```
  apt:
    arch:
      - amd64
```

which caused the above error. It would be great if that could be addressed as well.

**Comment by azubieta** [comment]
Thanks for testing.

The second error is quite weird could you please share which system are you using ?
