### ISSUE TITLE
RuntimeError: Main executable is not an elf executable

### ISSUE THREAD

**Issue by cat-master21** [AppImageCrafters/appimage-builder#256]
I have an isuue where appimage-builder fails because it thinks the binary is not an ELF executable. The binary is at: `https://github.com/proot-me/proot/releases/download/v5.3.0/proot-v5.3.0-x86_64-static`. I think this should work however.

```
Traceback (most recent call last):
  File "/tmp/.mount_appimaWDK0UH/usr/bin/appimage-builder", line 8, in <module>
    sys.exit(__main__())
  File "/tmp/.mount_appimaWDK0UH/usr/lib/python3.8/site-packages/appimagebuilder/__main__.py", line 50, in __main__
    invoker.execute(commands)
  File "/tmp/.mount_appimaWDK0UH/usr/lib/python3.8/site-packages/appimagebuilder/invoker.py", line 29, in execute
    command()
  File "/tmp/.mount_appimaWDK0UH/usr/lib/python3.8/site-packages/appimagebuilder/commands/setup_runtime.py", line 27, in __call__
    runtime.generate()
  File "/tmp/.mount_appimaWDK0UH/usr/lib/python3.8/site-packages/appimagebuilder/modules/setup/generator.py", line 88, in generate
    self._deploy_apprun(resolver)
  File "/tmp/.mount_appimaWDK0UH/usr/lib/python3.8/site-packages/appimagebuilder/modules/setup/generator.py", line 185, in _deploy_apprun
    raise RuntimeError(f"Main executable is not an elf executable: {bin_path}")
RuntimeError: Main executable is not an elf executable: /home/runner/work/Bottles/Bottles/AppDir/bin/proot
```

**Comment by cat-master21** [comment]
This on appimage-builder v1.0.3 by the way.
