### ISSUE TITLE
Docker HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by ruanformigoni** [AppImageCrafters/appimage-builder#257]
Hi, I'm getting the error below with docker, it seems the link is broken.

```txt
ERROR:root:There is not a prebuild runtime for the amd64 architecture. You will have to build the AppImage runtime manually.
INFO:root:Downloading runtime: https://github.com/AppImage/AppImageKit/releases/download/continuous/runtime-amd64
Traceback (most recent call last):
  File "/usr/local/bin/appimage-builder", line 11, in <module>
    load_entry_point('appimage-builder==0.9.1', 'console_scripts', 'appimage-builder')()
  File "/usr/local/lib/python3.6/dist-packages/appimage_builder-0.9.1-py3.6.egg/appimagebuilder/__main__.py", line 58, in __main__
    invoker.execute(commands)
  File "/usr/local/lib/python3.6/dist-packages/appimage_builder-0.9.1-py3.6.egg/appimagebuilder/invoker.py", line 41, in execute
    command()
  File "/usr/local/lib/python3.6/dist-packages/appimage_builder-0.9.1-py3.6.egg/appimagebuilder/commands/create_appimage.py", line 27, in __call__
    creator.create()
  File "/usr/local/lib/python3.6/dist-packages/appimage_builder-0.9.1-py3.6.egg/appimagebuilder/modules/appimage.py", line 52, in create
    self._download_runtime_if_required(runtime_path, runtime_url)
  File "/usr/local/lib/python3.6/dist-packages/appimage_builder-0.9.1-py3.6.egg/appimagebuilder/modules/appimage.py", line 68, in _download_runtime_if_required
    request.urlretrieve(runtime_url, runtime_path)
  File "/usr/lib/python3.6/urllib/request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

Docker image obtained with `docker pull appimagecrafters/appimage-builder:latest`

**Comment by ruanformigoni** [comment]
My mistake:
```yml
  AppImage:                                                                                                                                
    update-information: None                                                                                                               
    sign-key: None                                                                                                                         
    arch: x86_64   
```

Arch was `amd64`.
