### ISSUE TITLE
deploying via pacman require root permissions

### ISSUE THREAD

**Issue by Luciogi** [AppImageCrafters/appimage-builder#315]
When building appimage , it want to deploy fakeroot setup, and want root person to execute command `pacman-key`.
When Running `pacman-key` as normal user it works without root permission 
```
==> ERROR: pacman-key needs to be run as root for this operation.
ERROR:root:"['/tmp/.mount_appimazEA78C/usr/bin/fakeroot', '/usr/bin/pacman-key', '--config', '/home/oggy/appimage-builder/recipes/appimage-builder/appimage-build/pacman/pacman.conf', '--init']" execution failed
Traceback (most recent call last):
  File "/tmp/.mount_appimazEA78C/usr/bin/appimage-builder", line 8, in <module>
    sys.exit(__main__())
  File "/tmp/.mount_appimazEA78C/usr/lib/python3.8/site-packages/appimagebuilder/__main__.py", line 50, in __main__
    invoker.execute(commands)
  File "/tmp/.mount_appimazEA78C/usr/lib/python3.8/site-packages/appimagebuilder/invoker.py", line 29, in execute
    command()
  File "/tmp/.mount_appimazEA78C/usr/lib/python3.8/site-packages/appimagebuilder/commands/pacman_deploy.py", line 42, in __call__
    venv = Venv(
  File "/tmp/.mount_appimazEA78C/usr/lib/python3.8/site-packages/appimagebuilder/modules/deploy/pacman/venv.py", line 60, in __init__
    self._configure_keyring()
  File "/tmp/.mount_appimazEA78C/usr/lib/python3.8/site-packages/appimagebuilder/modules/deploy/pacman/venv.py", line 183, in _configure_keyring
    self._run_command("{fakeroot} {pacman-key} --config {config} --init")
  File "/tmp/.mount_appimazEA78C/usr/lib/python3.8/site-packages/appimagebuilder/modules/deploy/pacman/venv.py", line 234, in _run_command
    shell.assert_successful_result(_proc)
  File "/tmp/.mount_appimazEA78C/usr/lib/python3.8/site-packages/appimagebuilder/utils/shell.py", line 35, in assert_successful_result
    raise RuntimeError(
RuntimeError: "['/tmp/.mount_appimazEA78C/usr/bin/fakeroot', '/usr/bin/pacman-key', '--config', '/home/oggy/appimage-builder/recipes/appimage-builder/appimage-build/pacman/pacman.conf', '--init']" execution failed with code 1


```

**Comment by Luciogi** [comment]
I guess it is problem with my building env, closing for now
