### ISSUE TITLE
Tutorial Snippit Throws Error "chema.SchemaWrongKeyError: Wrong key 'allow_unauthenticated' ..."

### ISSUE THREAD

**Issue by dginovker** [AppImageCrafters/appimage-builder#61]
Version: I believe `v0.7.9`

(It's the latest version as of reporting, and I ran `sudo pip3 install git+https://github.com/AppImageCrafters/appimage-builder.git` to get it today)

Tutorial in mention: https://appimage-builder.readthedocs.io/en/latest/intro/tutorial.html

The `appimage-builder --generate` project runs no problem: https://i.imgur.com/V47rCQT.png

And it spits out the following yml: 

```
# appimage-builder recipe see https://appimage-builder.readthedocs.io for details
version: 1
AppDir:
  path: ./AppDir
  app_info:
    id: QtQuickControls2Application
    name: SimpleQtApp
    icon: QtQuickControls2Application
    version: latest
    exec: usr/bin/qt-appimage-template
    exec_args: $@
  runtime:
    env:
      APPDIR_LIBRARY_PATH: $APPDIR/lib/x86_64-linux-gnu
  apt:
    arch: amd64
    allow_unauthenticated: true
    sources:
    - sourceline: deb http://us.archive.ubuntu.com/ubuntu/ focal main restricted
    - sourceline: deb http://us.archive.ubuntu.com/ubuntu/ focal-updates main restricted
    - sourceline: deb http://us.archive.ubuntu.com/ubuntu/ focal universe
    - sourceline: deb http://us.archive.ubuntu.com/ubuntu/ focal-updates universe
    - sourceline: deb http://us.archive.ubuntu.com/ubuntu/ focal multiverse
    - sourceline: deb http://us.archive.ubuntu.com/ubuntu/ focal-updates multiverse
    - sourceline: deb http://us.archive.ubuntu.com/ubuntu/ focal-backports main restricted
        universe multiverse
    - sourceline: deb http://security.ubuntu.com/ubuntu focal-security main restricted
    - sourceline: deb http://security.ubuntu.com/ubuntu focal-security universe
    - sourceline: deb http://security.ubuntu.com/ubuntu focal-security multiverse
    - sourceline: deb [arch=amd64] https://packages.microsoft.com/ubuntu/20.04/prod
        focal main
    - sourceline: deb https://download.mono-project.com/repo/ubuntu stable-focal main
    include:
    - kimageformat-plugins
    - libbz2-1.0
    - libdbus-1-3
    - libexpat1
    - libgpg-error0
    - liblzma5
    - libpcre3
    - libqt5svg5
    - libsystemd0
    - libtinfo6
    - libuuid1
    - plasma-integration
    - qml-module-qtquick-controls2
    - qml-module-qtquick-layouts
    - qml-module-qtquick-templates2
    - qml-module-qtquick-window2
    - qml-module-qtquick2
    - qt5-image-formats-plugins
    exclude: []
  files:
    exclude:
    - usr/share/man
    - usr/share/doc/*/README.*
    - usr/share/doc/*/changelog.*
    - usr/share/doc/*/NEWS.*
    - usr/share/doc/*/TODO.*
  test:
    fedora:
      image: appimagecrafters/tests-env:fedora-30
      command: ./AppRun
      use_host_x: true
    debian:
      image: appimagecrafters/tests-env:debian-stable
      command: ./AppRun
      use_host_x: true
    arch:
      image: appimagecrafters/tests-env:archlinux-latest
      command: ./AppRun
      use_host_x: true
    centos:
      image: appimagecrafters/tests-env:centos-7
      command: ./AppRun
      use_host_x: true
    ubuntu:
      image: appimagecrafters/tests-env:ubuntu-xenial
      command: ./AppRun
      use_host_x: true
AppImage:
  arch: x86_64
  update-information: None
  sign-key: None
```

(Notice the `allow_unauthenticated: true`)

But when you run `appimage-builder` like the tutorial states, you get:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/schema.py", line 431, in validate
    return s.validate(data)
  File "/usr/local/lib/python3.8/dist-packages/schema.py", line 414, in validate
    raise SchemaWrongKeyError(message, e.format(data) if e else None)
schema.SchemaWrongKeyError: Wrong key 'allow_unauthenticated' in {'arch': 'amd64', 'allow_unauthenticated': True, 'sources': [{'sourceline': 'deb http://us.archive.ubuntu.com/ubuntu/ focal main restricted'}, {'sourceline': 'deb http://us.archive.ubuntu.com/ubuntu/ focal-updates main restricted'}, {'sourceline': 'deb http://us.archive.ubuntu.com/ubuntu/ focal universe'}, {'sourceline': 'deb http://us.archive.ubuntu.com/ubuntu/ focal-updates universe'}, {'sourceline': 'deb http://us.archive.ubuntu.com/ubuntu/ focal multiverse'}, {'sourceline': 'deb http://us.archive.ubuntu.com/ubuntu/ focal-updates multiverse'}, {'sourceline': 'deb http://us.archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse'}, {'sourceline': 'deb http://security.ubuntu.com/ubuntu focal-security main restricted'}, {'sourceline': 'deb http://security.ubuntu.com/ubuntu focal-security universe'}, {'sourceline': 'deb http://security.ubuntu.com/ubuntu focal-security multiverse'}, {'sourceline': 'deb [arch=amd64] https://packages.microsoft.com/ubuntu/20.04/prod focal main'}, {'sourceline': 'deb https://download.mono-project.com/repo/ubuntu stable-focal main'}], 'include': ['kimageformat-plugins', 'libbz2-1.0', 'libdbus-1-3', 'libexpat1', 'libgpg-error0', 'liblzma5', 'libpcre3', 'libqt5svg5', 'libsystemd0', 'libtinfo6', 'libuuid1', 'plasma-integration', 'qml-module-qtquick-controls2', 'qml-module-qtquick-layouts', 'qml-module-qtquick-templates2', 'qml-module-qtquick-window2', 'qml-module-qtquick2', 'qt5-image-formats-plugins'], 'exclude': []}

During handling of the above exception, another exception occurred:

...
```

If I remove the `allow_unauthenticated: true`, I get a lot of different errors that seem to relate to public key's not being available, but this part of the tutorial doesn't make sense to me so I can't fix it myself:

> To make an ubuntu keyring url you can use the following snippet, replace <KEY ID> by the value that comes after the NO_PUBKEY in the appimage-builder output:

> http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x<KEY ID>
> http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3B4FE6ACC0B21F32

(But I'm not sure where to put that snippet)

*****

OS: Ubuntu 20.04.1 LTS x86_64 
Kernel: 5.4.0-48-generic

**Comment by azubieta** [comment]
The recipe schema validation was introduced in the 0.7.8 release, this was clearly missing. Working on it.

**Comment by azubieta** [comment]
Should be fixed now, thanks for reporting :+1:

**Comment by dginovker** [comment]
Thank you so much!! ♥️
